import {
  ExFormItemCategory,
  newBooleanOptions,
  newStringOptions,
  PluginCategory,
} from "@/constants";
import type { ExFormItem } from "@/components/ex-form";

/** Namespaced translator, i.e. the value of `useI18n("plugin")`. */
type Translate = (key: string) => string;

/**
 * Extra form fields a plugin category contributes, on top of the shared
 * category / name / step fields the page always renders.
 *
 * Kept out of the page because every builder is pure: it reads the saved plugin
 * config and the translator, nothing else. Adding a plugin means adding a key
 * here, not editing a switch inside a component.
 */
export type PluginFieldsBuilder = (
  conf: Record<string, unknown>,
  t: Translate,
) => ExFormItem[];

export const PLUGIN_FIELDS: Partial<
  Record<PluginCategory, PluginFieldsBuilder>
> = {
  [PluginCategory.STATS]: (conf, t) => [
    {
      name: "path",
      label: t("statsPath"),
      placeholder: t("statsPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.PING]: (conf, t) => [
    {
      name: "path",
      label: t("pingPath"),
      placeholder: t("pingPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.ADMIN]: (conf, t) => [
    {
      name: "path",
      label: t("adminPath"),
      placeholder: t("adminPathPlaceholder"),
      defaultValue: (conf.path || "") as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max_age",
      label: t("adminMaxAge"),
      placeholder: t("adminMaxAgePlaceholder"),
      defaultValue: (conf.max_age || "") as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "ip_fail_limit",
      label: t("adminIpFailLimit"),
      placeholder: t("adminIpFailLimitPlaceholder"),
      defaultValue: Number(conf.ip_fail_limit || 0),
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "authorizations",
      label: t("adminAuthorization"),
      placeholder: t("adminAuthorizationPlaceholder"),
      defaultValue: (conf.authorizations || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "readonly_authorizations",
      label: t("adminReadonlyAuthorization"),
      placeholder: t("adminAuthorizationPlaceholder"),
      tips: t("adminReadonlyAuthorizationTips"),
      defaultValue: (conf.readonly_authorizations || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "tokens",
      label: t("adminTokens"),
      placeholder: t("adminTokensPlaceholder"),
      tips: t("adminTokensTips"),
      defaultValue: (conf.tokens || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "readonly_tokens",
      label: t("adminReadonlyTokens"),
      placeholder: t("adminTokensPlaceholder"),
      tips: t("adminReadonlyTokensTips"),
      defaultValue: (conf.readonly_tokens || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.DIRECTORY]: (conf, t) => [
    {
      name: "path",
      label: t("dirPath"),
      placeholder: t("dirPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "index",
      label: t("dirIndex"),
      placeholder: t("dirIndexPlaceholder"),
      defaultValue: conf.index as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "chunk_size",
      label: t("dirChunkSize"),
      placeholder: t("dirChunkSizePlaceholder"),
      defaultValue: conf.chunk_size as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "autoindex",
      label: t("dirAutoIndex"),
      placeholder: "",
      defaultValue: conf.autoindex as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "max_age",
      label: t("dirMaxAge"),
      placeholder: t("dirMaxAgePlaceholder"),
      defaultValue: conf.max_age as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "private",
      label: t("dirCachePrivate"),
      placeholder: "",
      defaultValue: conf.private as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "charset",
      label: t("dirCharset"),
      placeholder: t("dirCharsetPlaceholder"),
      defaultValue: conf.charset as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "download",
      label: t("dirDownload"),
      placeholder: "",
      defaultValue: conf.download as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "follow_symlinks",
      label: t("dirFollowSymlinks"),
      placeholder: "",
      tips: t("dirFollowSymlinksTips"),
      defaultValue: conf.follow_symlinks as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "hidden",
      label: t("dirHidden"),
      placeholder: "",
      tips: t("dirHiddenTips"),
      defaultValue: conf.hidden as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "fallback",
      label: t("dirFallback"),
      placeholder: t("dirFallbackPlaceholder"),
      tips: t("dirFallbackTips"),
      defaultValue: conf.fallback as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "precompressed",
      label: t("dirPrecompressed"),
      placeholder: t("dirPrecompressedPlaceholder"),
      tips: t("dirPrecompressedTips"),
      defaultValue: conf.precompressed as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "headers",
      label: t("dirHeaderName"),
      placeholder: t("dirHeaderNamePlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
  ],
  [PluginCategory.MOCK]: (conf, t) => [
    {
      name: "path",
      label: t("mockPath"),
      placeholder: t("mockPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status",
      label: t("mockStatus"),
      placeholder: t("mockStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "delay",
      label: t("mockResponseDelay"),
      placeholder: t("mockResponseDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "headers",
      label: t("mockHeaderName"),
      placeholder: t("mockHeaderNamePlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "data",
      label: t("mockData"),
      placeholder: t("mockDataPlaceholder"),
      defaultValue: conf.data as string,
      span: 6,
      category: ExFormItemCategory.TEXTAREA,
      rows: 5,
    },
  ],
  [PluginCategory.REDIRECT]: (conf, t) => [
    {
      name: "prefix",
      label: t("redirectPrefix"),
      placeholder: t("redirectPrefixPlaceholder"),
      defaultValue: conf.prefix as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status",
      label: t("redirectStatus"),
      placeholder: t("redirectStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "host",
      label: t("redirectHost"),
      placeholder: t("redirectHostPlaceholder"),
      tips: t("redirectHostTips"),
      defaultValue: conf.host as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "rules",
      label: t("redirectRules"),
      placeholder: t("redirectRulesPlaceholder"),
      tips: t("redirectRulesTips"),
      defaultValue: conf.rules as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "http_to_https",
      label: t("redirectHttps"),
      placeholder: "",
      defaultValue: conf.http_to_https as boolean,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.CACHE]: (conf, t) => [
    {
      name: "directory",
      label: t("cacheDirectory"),
      placeholder: t("cacheDirectoryPlaceholder"),
      defaultValue: conf.directory as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "lock",
      label: t("cacheLock"),
      placeholder: t("cacheLockPlaceholder"),
      defaultValue: conf.lock as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "lock_retries",
      label: t("cacheLockRetries"),
      placeholder: t("cacheLockRetriesPlaceholder"),
      defaultValue: conf.lock_retries as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "max_file_size",
      label: t("cacheMaxFileSize"),
      placeholder: t("cacheMaxFileSizePlaceholder"),
      defaultValue: conf.max_file_size as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "namespace",
      label: t("cacheNamespace"),
      placeholder: t("cacheNamespacePlaceholder"),
      defaultValue: conf.namespace as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max_ttl",
      label: t("cacheMaxTtl"),
      placeholder: t("cacheMaxTtlPlaceholder"),
      defaultValue: conf.max_ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "eviction",
      label: t("cacheEviction"),
      placeholder: "",
      defaultValue: conf.eviction as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "predictor",
      label: t("cachePredictor"),
      placeholder: "",
      defaultValue: conf.predictor as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "skip",
      label: t("cacheSkip"),
      placeholder: t("cacheSkipPlaceholder"),
      defaultValue: conf.skip as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "check_cache_control",
      label: t("checkCacheControl"),
      placeholder: "",
      defaultValue: conf.check_cache_control as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "headers",
      label: t("cacheHeaders"),
      placeholder: t("cacheHeadersPlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "vary_headers",
      label: t("cacheVaryHeaders"),
      placeholder: t("cacheVaryHeadersPlaceholder"),
      defaultValue: conf.vary_headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "purge_ip_list",
      label: t("cachePurgeIpList"),
      placeholder: t("cachePurgeIpListPlaceholder"),
      defaultValue: conf.purge_ip_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "default_ttl",
      label: t("cacheDefaultTtl"),
      placeholder: t("cacheDefaultTtlPlaceholder"),
      tips: t("cacheDefaultTtlTips"),
      defaultValue: conf.default_ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "respect_client_no_cache",
      label: t("cacheRespectClientNoCache"),
      placeholder: "",
      tips: t("cacheRespectClientNoCacheTips"),
      defaultValue: conf.respect_client_no_cache as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "status_ttl",
      label: t("cacheStatusTtl"),
      placeholder: t("cacheStatusTtlPlaceholder"),
      tips: t("cacheStatusTtlTips"),
      defaultValue: conf.status_ttl as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "bypass_headers",
      label: t("cacheBypassHeaders"),
      placeholder: t("cacheBypassHeadersPlaceholder"),
      tips: t("cacheBypassTips"),
      defaultValue: conf.bypass_headers as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "bypass_cookies",
      label: t("cacheBypassCookies"),
      placeholder: t("cacheBypassCookiesPlaceholder"),
      tips: t("cacheBypassTips"),
      defaultValue: conf.bypass_cookies as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "ignore_query",
      label: t("cacheIgnoreQuery"),
      placeholder: t("cacheIgnoreQueryPlaceholder"),
      tips: t("cacheQueryTips"),
      defaultValue: conf.ignore_query as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "query_allow",
      label: t("cacheQueryAllow"),
      placeholder: t("cacheQueryAllowPlaceholder"),
      tips: t("cacheQueryTips"),
      defaultValue: conf.query_allow as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.REQUEST_ID]: (conf, t) => [
    {
      name: "algorithm",
      label: t("requestIdAlgo"),
      placeholder: t("requestIdAlgoPlaceholder"),
      defaultValue: conf.algorithm as string,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["uuid", "nanoid"], false),
    },
    {
      name: "size",
      label: t("requestIdLength"),
      placeholder: t("requestIdLengthPlaceholder"),
      defaultValue: conf.size as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "header_name",
      label: t("requestIdHeaderName"),
      placeholder: t("requestIdHeaderNamePlaceholder"),
      defaultValue: conf.header_name as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.COMPRESSION]: (conf, t) => [
    {
      name: "gzip_level",
      label: t("compressionGzipLevel"),
      placeholder: t("compressionGzipLevelPlaceholder"),
      defaultValue: conf.gzip_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "br_level",
      label: t("compressionBrLevel"),
      placeholder: t("compressionBrLevelPlaceholder"),
      defaultValue: conf.br_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "zstd_level",
      label: t("compressionZstdLevel"),
      placeholder: t("compressionZstdLevelPlaceholder"),
      defaultValue: conf.zstd_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "min_length",
      label: t("compressionMinLength"),
      placeholder: t("compressionMinLengthPlaceholder"),
      defaultValue: conf.min_length as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "decompression",
      label: t("compressionDecompression"),
      placeholder: "",
      defaultValue: conf.decompression as boolean,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "mode",
      label: t("compressionMode"),
      placeholder: "",
      defaultValue: conf.mode as string,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["response", "upstream"], false),
    },
    {
      name: "types",
      label: t("compressionTypes"),
      placeholder: t("compressionTypesPlaceholder"),
      tips: t("compressionTypesTips"),
      defaultValue: conf.types as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "skip",
      label: t("compressionSkip"),
      placeholder: t("compressionSkipPlaceholder"),
      tips: t("compressionSkipTips"),
      defaultValue: conf.skip as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.ACCEPT_ENCODING]: (conf, t) => [
    {
      name: "encodings",
      label: t("acceptEncodingList"),
      placeholder: t("acceptEncodingListPlaceholder"),
      defaultValue: conf.encodings as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "only_one_encoding",
      label: t("acceptEncodingOnlyOne"),
      placeholder: "",
      defaultValue: conf.only_one_encoding as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.KEY_AUTH]: (conf, t) => [
    {
      name: "query",
      label: t("keyAuthQuery"),
      placeholder: t("keyAuthQueryPlaceholder"),
      defaultValue: conf.query as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "header",
      label: t("keyAuthHeader"),
      placeholder: t("keyAuthHeaderPlaceholder"),
      defaultValue: conf.header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "delay",
      label: t("keyAuthFailDelay"),
      placeholder: t("keyAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "hide_credentials",
      label: t("keyAuthHideCredentials"),
      placeholder: t("keyAuthHideCredentialsPlaceholder"),
      defaultValue: conf.hide_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "keys",
      label: t("keyAuthValues"),
      placeholder: t("keyAuthValuesPlaceholder"),
      defaultValue: conf.keys as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.BASIC_AUTH]: (conf, t) => [
    {
      name: "authorizations",
      label: t("basicAuthList"),
      placeholder: t("basicAuthListPlaceholder"),
      defaultValue: conf.authorizations as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "htpasswd",
      label: t("basicAuthHtpasswd"),
      placeholder: t("basicAuthHtpasswdPlaceholder"),
      tips: t("basicAuthHtpasswdTips"),
      defaultValue: conf.htpasswd as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "realm",
      label: t("basicAuthRealm"),
      placeholder: t("basicAuthRealmPlaceholder"),
      defaultValue: conf.realm as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "delay",
      label: t("basicAuthFailDelay"),
      placeholder: t("basicAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "hide_credentials",
      label: t("basicAuthHideCredentials"),
      placeholder: t("basicAuthHideCredentialsPlaceholder"),
      defaultValue: conf.hide_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "ip_fail_limit",
      label: t("basicAuthIpFailLimit"),
      placeholder: t("basicAuthIpFailLimitPlaceholder"),
      tips: t("basicAuthIpFailLimitTips"),
      defaultValue: Number(conf.ip_fail_limit || 0),
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "ip_fail_window",
      label: t("basicAuthIpFailWindow"),
      placeholder: t("basicAuthIpFailWindowPlaceholder"),
      defaultValue: conf.ip_fail_window as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.JWT]: (conf, t) => [
    {
      name: "header",
      label: t("jwtAuthHeader"),
      placeholder: t("jwtAuthHeaderPlaceholder"),
      defaultValue: conf.header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "query",
      label: t("jwtAuthQuery"),
      placeholder: t("jwtAuthQueryPlaceholder"),
      defaultValue: conf.query as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "cookie",
      label: t("jwtAuthCookie"),
      placeholder: t("jwtAuthCookiePlaceholder"),
      defaultValue: conf.cookie as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "auth_path",
      label: t("jwtSignPath"),
      placeholder: t("jwtSignPathPlaceholder"),
      defaultValue: conf.auth_path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "delay",
      label: t("jwtAuthFailDelay"),
      placeholder: t("jwtAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "algorithm",
      label: t("jwtSignAlgorithm"),
      placeholder: "",
      tips: t("jwtSignAlgorithmTips"),
      defaultValue: (conf.algorithm as string) || "",
      span: 3,
      category: ExFormItemCategory.SELECT,
      options: newStringOptions(
        [
          "HS256",
          "HS384",
          "HS512",
          "RS256",
          "RS384",
          "RS512",
          "PS256",
          "PS384",
          "PS512",
          "ES256",
          "ES384",
          "EdDSA",
        ],
        true,
      ),
    },
    {
      name: "secret",
      label: t("jwtAuthSecret"),
      placeholder: t("jwtAuthSecretPlaceholder"),
      defaultValue: conf.secret as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "public_key",
      label: t("jwtPublicKey"),
      placeholder: t("jwtPublicKeyPlaceholder"),
      tips: t("jwtPublicKeyTips"),
      defaultValue: conf.public_key as string,
      span: 6,
      category: ExFormItemCategory.TEXTAREA,
    },
    {
      name: "jwks_url",
      label: t("jwtJwksUrl"),
      placeholder: t("jwtJwksUrlPlaceholder"),
      tips: t("jwtJwksUrlTips"),
      defaultValue: conf.jwks_url as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "jwks_ttl",
      label: t("jwtJwksTtl"),
      placeholder: t("jwtJwksTtlPlaceholder"),
      defaultValue: conf.jwks_ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "require_exp",
      label: t("jwtRequireExp"),
      placeholder: "",
      tips: t("jwtRequireExpTips"),
      defaultValue: conf.require_exp as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "leeway",
      label: t("jwtLeeway"),
      placeholder: t("jwtLeewayPlaceholder"),
      tips: t("jwtLeewayTips"),
      defaultValue: conf.leeway as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "issuers",
      label: t("jwtIssuers"),
      placeholder: t("jwtIssuersPlaceholder"),
      tips: t("jwtIssuersTips"),
      defaultValue: conf.issuers as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "audiences",
      label: t("jwtAudiences"),
      placeholder: t("jwtAudiencesPlaceholder"),
      tips: t("jwtAudiencesTips"),
      defaultValue: conf.audiences as string[],
      span: 3,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "required_claims",
      label: t("jwtRequiredClaims"),
      placeholder: t("jwtRequiredClaimsPlaceholder"),
      tips: t("jwtRequiredClaimsTips"),
      defaultValue: conf.required_claims as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "claims_to_headers",
      label: t("jwtClaimsToHeaders"),
      placeholder: t("jwtClaimsToHeadersPlaceholder"),
      tips: t("jwtClaimsToHeadersTips"),
      defaultValue: conf.claims_to_headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.FORWARD_AUTH]: (conf, t) => [
    {
      name: "auth_url",
      label: t("forwardAuthUrl"),
      placeholder: t("forwardAuthUrlPlaceholder"),
      defaultValue: conf.auth_url as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "timeout",
      label: t("forwardAuthTimeout"),
      placeholder: t("forwardAuthTimeoutPlaceholder"),
      defaultValue: conf.timeout as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "request_headers",
      label: t("forwardAuthRequestHeaders"),
      placeholder: t("forwardAuthRequestHeadersPlaceholder"),
      tips: t("forwardAuthRequestHeadersTips"),
      defaultValue: (conf.request_headers || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "add_headers",
      label: t("forwardAuthAddHeaders"),
      placeholder: t("forwardAuthAddHeadersPlaceholder"),
      tips: t("forwardAuthAddHeadersTips"),
      defaultValue: (conf.add_headers || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.COMBINED_AUTH]: (conf, t) => [
    {
      name: "authorizations",
      label: t("combinedAuthAuthorizations"),
      placeholder: "",
      defaultValue: conf.authorizations as [],
      span: 6,
      category: ExFormItemCategory.COMBINED_AUTHS,
    },
  ],
  [PluginCategory.LIMIT]: (conf, t) => [
    {
      name: "type",
      label: t("limitCategory"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["rate", "inflight"], true),
    },
    {
      name: "tag",
      label: t("limitTag"),
      placeholder: "",
      defaultValue: conf.tag as string,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["cookie", "header", "query", "ip"], true),
    },
    {
      name: "key",
      label: t("limitKey"),
      placeholder: t("limitKeyPlaceholder"),
      defaultValue: conf.key as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max",
      label: t("limitMax"),
      placeholder: t("limitMaxPlaceholder"),
      defaultValue: conf.max as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "interval",
      label: t("limitInterval"),
      placeholder: t("limitIntervalPlaceholder"),
      defaultValue: conf.interval as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "headers",
      label: t("limitHeaders"),
      placeholder: "",
      tips: t("limitHeadersTips"),
      defaultValue: conf.headers as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "missing_key",
      label: t("limitMissingKey"),
      placeholder: "",
      tips: t("limitMissingKeyTips"),
      defaultValue: (conf.missing_key as string) || "",
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["pass", "reject"], true, true),
    },
    {
      name: "status",
      label: t("limitStatus"),
      placeholder: t("limitStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "message",
      label: t("limitMessage"),
      placeholder: t("limitMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.IP_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("ipRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "ip_list",
      label: t("ipList"),
      placeholder: t("ipListPlaceholder"),
      defaultValue: conf.ip_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("ipRestrictionMessage"),
      placeholder: t("ipRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.GEO_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("geoRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny", "reporting"], true),
    },
    {
      name: "country_codes",
      label: t("geoRestrictionCountryCodes"),
      placeholder: t("geoRestrictionCountryCodesPlaceholder"),
      defaultValue: conf.country_codes as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("geoRestrictionMessage"),
      placeholder: t("geoRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.REFERER_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("refererRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "referer_list",
      label: t("refererList"),
      placeholder: t("refererListPlaceholder"),
      defaultValue: conf.referer_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("refererRestrictionMessage"),
      placeholder: t("refererRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.UA_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("uaRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "ua_list",
      label: t("uaList"),
      placeholder: t("uaListPlaceholder"),
      defaultValue: conf.ua_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("uaRestrictionMessage"),
      placeholder: t("uaRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.CSRF]: (conf, t) => [
    {
      name: "token_path",
      label: t("csrfTokenPath"),
      placeholder: t("csrfTokenPathPlaceholder"),
      defaultValue: conf.token_path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "name",
      label: t("csrfName"),
      placeholder: t("csrfNamePlaceholder"),
      defaultValue: conf.name as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "key",
      label: t("csrfKey"),
      placeholder: t("csrfKeyPlaceholder"),
      defaultValue: conf.key as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "ttl",
      label: t("csrfTtl"),
      placeholder: t("csrfTtlPlaceholder"),
      defaultValue: conf.ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.CORS]: (conf, t) => [
    {
      name: "path",
      label: t("corsPath"),
      placeholder: t("corsPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_origin",
      label: t("corsAllowOrigin"),
      placeholder: t("corsAllowOriginPlaceholder"),
      defaultValue: conf.allow_origin as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_origins",
      label: t("corsAllowOrigins"),
      placeholder: t("corsAllowOriginsPlaceholder"),
      tips: t("corsAllowOriginsTips"),
      defaultValue: conf.allow_origins as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "allow_methods",
      label: t("corsAllowMethods"),
      placeholder: t("corsAllowMethodsPlaceholder"),
      defaultValue: conf.allow_methods as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_headers",
      label: t("corsAllowHeaders"),
      placeholder: t("corsAllowHeadersPlaceholder"),
      defaultValue: conf.allow_headers as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_credentials",
      label: t("corsAllowCredentials"),
      placeholder: "",
      defaultValue: conf.allow_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "max_age",
      label: t("corsMaxAge"),
      placeholder: t("corsMaxAgePlaceholder"),
      defaultValue: conf.max_age as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "expose_headers",
      label: t("corsExposeHeaders"),
      placeholder: t("corsExposeHeadersPlaceholder"),
      defaultValue: conf.expose_headers as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.RESPONSE_HEADERS]: (conf, t) => [
    {
      name: "add_headers",
      label: t("responseHeadersAddHeader"),
      placeholder: t("responseHeadersAddHeaderPlaceholder"),
      defaultValue: conf.add_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers",
      label: t("responseHeadersSetHeader"),
      placeholder: t("responseHeadersSetHeaderPlaceholder"),
      defaultValue: conf.set_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "remove_headers",
      label: t("responseHeadersRemoveHeader"),
      placeholder: t("responseHeadersRemoveHeaderPlaceholder"),
      defaultValue: conf.remove_headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "rename_headers",
      label: t("responseHeadersRenameHeader"),
      placeholder: t("responseHeadersRenamePlaceholder"),
      defaultValue: conf.rename_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers_not_exists",
      label: t("responseHeadersSetHeaderNotExists"),
      placeholder: t("responseHeadersSetHeaderNotExistsPlaceholder"),
      defaultValue: conf.set_headers_not_exists as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "mode",
      label: t("responseHeadersMode"),
      placeholder: t("responseHeadersModePlaceholder"),
      defaultValue: conf.mode as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["upstream", "response"], true),
    },
    {
      name: "preset",
      label: t("responseHeadersPreset"),
      placeholder: "",
      tips: t("responseHeadersPresetTips"),
      defaultValue: (conf.preset as string) || "",
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["security"], true, true),
    },
    {
      name: "always",
      label: t("responseHeadersAlways"),
      placeholder: "",
      tips: t("responseHeadersAlwaysTips"),
      defaultValue: conf.always as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.MAINTENANCE]: (conf, t) => [
    {
      name: "enabled",
      label: t("maintenanceEnabled"),
      placeholder: "",
      tips: t("maintenanceEnabledTips"),
      defaultValue: conf.enabled as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "status",
      label: t("maintenanceStatus"),
      placeholder: t("maintenanceStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "retry_after",
      label: t("maintenanceRetryAfter"),
      placeholder: t("maintenanceRetryAfterPlaceholder"),
      defaultValue: conf.retry_after as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_header",
      label: t("maintenanceAllowHeader"),
      placeholder: t("maintenanceAllowHeaderPlaceholder"),
      tips: t("maintenanceAllowHeaderTips"),
      defaultValue: conf.allow_header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_ip_list",
      label: t("maintenanceAllowIpList"),
      placeholder: t("maintenanceAllowIpListPlaceholder"),
      tips: t("maintenanceAllowIpListTips"),
      defaultValue: conf.allow_ip_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("maintenanceMessage"),
      placeholder: t("maintenanceMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "html",
      label: t("maintenanceHtml"),
      placeholder: t("maintenanceHtmlPlaceholder"),
      defaultValue: conf.html as string,
      span: 6,
      category: ExFormItemCategory.TEXTAREA,
      rows: 5,
    },
  ],
  [PluginCategory.HEALTH]: (conf, t) => [
    {
      name: "path",
      label: t("healthPath"),
      placeholder: t("healthPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "min_healthy",
      label: t("healthMinHealthy"),
      placeholder: t("healthMinHealthyPlaceholder"),
      defaultValue: conf.min_healthy as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "upstreams",
      label: t("healthUpstreams"),
      placeholder: t("healthUpstreamsPlaceholder"),
      tips: t("healthUpstreamsTips"),
      defaultValue: conf.upstreams as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.REQUEST_HEADERS]: (conf, t) => [
    {
      name: "add_headers",
      label: t("requestHeadersAddHeader"),
      placeholder: t("requestHeadersHeaderPlaceholder"),
      defaultValue: conf.add_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers",
      label: t("requestHeadersSetHeader"),
      placeholder: t("requestHeadersHeaderPlaceholder"),
      defaultValue: conf.set_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers_not_exists",
      label: t("requestHeadersSetHeaderNotExists"),
      placeholder: t("requestHeadersHeaderPlaceholder"),
      defaultValue: conf.set_headers_not_exists as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "remove_headers",
      label: t("requestHeadersRemoveHeader"),
      placeholder: t("requestHeadersRemoveHeaderPlaceholder"),
      defaultValue: conf.remove_headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "rename_headers",
      label: t("requestHeadersRenameHeader"),
      placeholder: t("requestHeadersRenamePlaceholder"),
      defaultValue: conf.rename_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
  ],
  [PluginCategory.URI_BLOCK]: (conf, t) => [
    {
      name: "paths",
      label: t("uriBlockPaths"),
      placeholder: t("uriBlockPathsPlaceholder"),
      tips: t("uriBlockPathsTips"),
      defaultValue: conf.paths as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "queries",
      label: t("uriBlockQueries"),
      placeholder: t("uriBlockQueriesPlaceholder"),
      tips: t("uriBlockQueriesTips"),
      defaultValue: conf.queries as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "methods",
      label: t("uriBlockMethods"),
      placeholder: t("uriBlockMethodsPlaceholder"),
      tips: t("uriBlockMethodsTips"),
      defaultValue: conf.methods as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "status",
      label: t("uriBlockStatus"),
      placeholder: t("uriBlockStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "message",
      label: t("uriBlockMessage"),
      placeholder: t("uriBlockMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.SUB_FILTER]: (conf, t) => [
    {
      name: "path",
      label: t("subFilterPath"),
      placeholder: t("subFilterPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status_codes",
      label: t("subFilterStatusCodes"),
      placeholder: t("subFilterStatusCodesPlaceholder"),
      defaultValue: conf.status_codes as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "filters",
      label: t("subFilterFilters"),
      placeholder: t("subFilterFiltersPlaceholder"),
      defaultValue: conf.filters as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.IMAGE_OPTIM]: (conf, t) => [
    {
      name: "output_types",
      label: t("imageOptimOutputTypes"),
      placeholder: t("imageOptimOutputTypesPlaceholder"),
      defaultValue: conf.output_types as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "png_quality",
      label: t("imageOptimPngQuality"),
      placeholder: t("imageOptimPngQualityPlaceholder"),
      defaultValue: conf.png_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "jpeg_quality",
      label: t("imageOptimJpegQuality"),
      placeholder: t("imageOptimJpegQualityPlaceholder"),
      defaultValue: conf.jpeg_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "avif_quality",
      label: t("imageOptimAvifQuality"),
      placeholder: t("imageOptimAvifQualityPlaceholder"),
      defaultValue: conf.avif_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "avif_speed",
      label: t("imageOptimAvifSpeed"),
      placeholder: t("imageOptimAvifSpeedPlaceholder"),
      defaultValue: conf.avif_speed as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
  ],
  [PluginCategory.TRAFFIC_SPLITTING]: (conf, t) => [
    {
      name: "upstream",
      label: t("trafficSplittingUpstream"),
      placeholder: t("trafficSplittingUpstreamPlaceholder"),
      defaultValue: conf.upstream as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "weight",
      label: t("trafficSplittingWeight"),
      placeholder: t("trafficSplittingWeightPlaceholder"),
      defaultValue: conf.weight as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "stickiness",
      label: t("trafficSplittingStickiness"),
      placeholder: t("trafficSplittingStickinessPlaceholder"),
      defaultValue: conf.stickiness as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "sticky_cookie",
      label: t("trafficSplittingStickyCookie"),
      placeholder: t("trafficSplittingStickyCookiePlaceholder"),
      defaultValue: conf.sticky_cookie as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "sticky_header",
      label: t("trafficSplittingStickyHeader"),
      placeholder: t("trafficSplittingStickyHeaderPlaceholder"),
      defaultValue: conf.sticky_header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "matcher",
      label: t("trafficSplittingMatcher"),
      placeholder: t("trafficSplittingMatcherPlaceholder"),
      defaultValue: conf.matcher as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
};
