import {
  ExFormItemCategory,
  newBooleanOptions,
  newStringOptions,
  PluginCategory,
} from "@/constants";
import type { ExFormItem } from "@/components/ex-form";

/** Namespaced translator, i.e. the value of `useI18n("plugin")`. */
type Translate = (key: string) => string;

/**
 * Extra form fields a plugin category contributes, on top of the shared
 * category / name / step fields the page always renders.
 *
 * Kept out of the page because every builder is pure: it reads the saved plugin
 * config and the translator, nothing else. Adding a plugin means adding a key
 * here, not editing a switch inside a component.
 */
export type PluginFieldsBuilder = (
  conf: Record<string, unknown>,
  t: Translate,
) => ExFormItem[];

export const PLUGIN_FIELDS: Partial<
  Record<PluginCategory, PluginFieldsBuilder>
> = {
  [PluginCategory.STATS]: (conf, t) => [
    {
      name: "path",
      label: t("statsPath"),
      placeholder: t("statsPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.PING]: (conf, t) => [
    {
      name: "path",
      label: t("pingPath"),
      placeholder: t("pingPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.ADMIN]: (conf, t) => [
    {
      name: "path",
      label: t("adminPath"),
      placeholder: t("adminPathPlaceholder"),
      defaultValue: (conf.path || "") as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max_age",
      label: t("adminMaxAge"),
      placeholder: t("adminMaxAgePlaceholder"),
      defaultValue: (conf.max_age || "") as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "ip_fail_limit",
      label: t("adminIpFailLimit"),
      placeholder: t("adminIpFailLimitPlaceholder"),
      defaultValue: Number(conf.ip_fail_limit || 0),
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "authorizations",
      label: t("adminAuthorization"),
      placeholder: t("adminAuthorizationPlaceholder"),
      defaultValue: (conf.authorizations || []) as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.DIRECTORY]: (conf, t) => [
    {
      name: "path",
      label: t("dirPath"),
      placeholder: t("dirPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "index",
      label: t("dirIndex"),
      placeholder: t("dirIndexPlaceholder"),
      defaultValue: conf.index as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "chunk_size",
      label: t("dirChunkSize"),
      placeholder: t("dirChunkSizePlaceholder"),
      defaultValue: conf.chunk_size as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "autoindex",
      label: t("dirAutoIndex"),
      placeholder: "",
      defaultValue: conf.autoindex as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "max_age",
      label: t("dirMaxAge"),
      placeholder: t("dirMaxAgePlaceholder"),
      defaultValue: conf.max_age as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "private",
      label: t("dirCachePrivate"),
      placeholder: "",
      defaultValue: conf.private as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "charset",
      label: t("dirCharset"),
      placeholder: t("dirCharsetPlaceholder"),
      defaultValue: conf.charset as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "download",
      label: t("dirDownload"),
      placeholder: "",
      defaultValue: conf.download as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "headers",
      label: t("dirHeaderName"),
      placeholder: t("dirHeaderNamePlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
  ],
  [PluginCategory.MOCK]: (conf, t) => [
    {
      name: "path",
      label: t("mockPath"),
      placeholder: t("mockPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status",
      label: t("mockStatus"),
      placeholder: t("mockStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "delay",
      label: t("mockResponseDelay"),
      placeholder: t("mockResponseDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "headers",
      label: t("mockHeaderName"),
      placeholder: t("mockHeaderNamePlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "data",
      label: t("mockData"),
      placeholder: t("mockDataPlaceholder"),
      defaultValue: conf.data as string,
      span: 6,
      category: ExFormItemCategory.TEXTAREA,
      rows: 5,
    },
  ],
  [PluginCategory.REDIRECT]: (conf, t) => [
    {
      name: "prefix",
      label: t("redirectPrefix"),
      placeholder: t("redirectPrefixPlaceholder"),
      defaultValue: conf.prefix as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status",
      label: t("redirectStatus"),
      placeholder: t("redirectStatusPlaceholder"),
      defaultValue: conf.status as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "http_to_https",
      label: t("redirectHttps"),
      placeholder: "",
      defaultValue: conf.http_to_https as boolean,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.CACHE]: (conf, t) => [
    {
      name: "directory",
      label: t("cacheDirectory"),
      placeholder: t("cacheDirectoryPlaceholder"),
      defaultValue: conf.directory as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "lock",
      label: t("cacheLock"),
      placeholder: t("cacheLockPlaceholder"),
      defaultValue: conf.lock as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max_file_size",
      label: t("cacheMaxFileSize"),
      placeholder: t("cacheMaxFileSizePlaceholder"),
      defaultValue: conf.max_file_size as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "namespace",
      label: t("cacheNamespace"),
      placeholder: t("cacheNamespacePlaceholder"),
      defaultValue: conf.namespace as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max_ttl",
      label: t("cacheMaxTtl"),
      placeholder: t("cacheMaxTtlPlaceholder"),
      defaultValue: conf.max_ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "eviction",
      label: t("cacheEviction"),
      placeholder: "",
      defaultValue: conf.eviction as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "predictor",
      label: t("cachePredictor"),
      placeholder: "",
      defaultValue: conf.predictor as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "skip",
      label: t("cacheSkip"),
      placeholder: t("cacheSkipPlaceholder"),
      defaultValue: conf.skip as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "check_cache_control",
      label: t("checkCacheControl"),
      placeholder: "",
      defaultValue: conf.check_cache_control as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "headers",
      label: t("cacheHeaders"),
      placeholder: t("cacheHeadersPlaceholder"),
      defaultValue: conf.headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "purge_ip_list",
      label: t("cachePurgeIpList"),
      placeholder: t("cachePurgeIpListPlaceholder"),
      defaultValue: conf.purge_ip_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.REQUEST_ID]: (conf, t) => [
    {
      name: "algorithm",
      label: t("requestIdAlgo"),
      placeholder: t("requestIdAlgoPlaceholder"),
      defaultValue: conf.algorithm as string,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["uuid", "nanoid"], false),
    },
    {
      name: "size",
      label: t("requestIdLength"),
      placeholder: t("requestIdLengthPlaceholder"),
      defaultValue: conf.size as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "header_name",
      label: t("requestIdHeaderName"),
      placeholder: t("requestIdHeaderNamePlaceholder"),
      defaultValue: conf.header_name as string,
      span: 2,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.COMPRESSION]: (conf, t) => [
    {
      name: "gzip_level",
      label: t("compressionGzipLevel"),
      placeholder: t("compressionGzipLevelPlaceholder"),
      defaultValue: conf.gzip_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "br_level",
      label: t("compressionBrLevel"),
      placeholder: t("compressionBrLevelPlaceholder"),
      defaultValue: conf.br_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "zstd_level",
      label: t("compressionZstdLevel"),
      placeholder: t("compressionZstdLevelPlaceholder"),
      defaultValue: conf.zstd_level as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "min_length",
      label: t("compressionMinLength"),
      placeholder: t("compressionMinLengthPlaceholder"),
      defaultValue: conf.min_length as number,
      span: 2,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "decompression",
      label: t("compressionDecompression"),
      placeholder: "",
      defaultValue: conf.decompression as boolean,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "mode",
      label: t("compressionMode"),
      placeholder: "",
      defaultValue: conf.mode as string,
      span: 2,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["response", "upstream"], false),
    },
  ],
  [PluginCategory.ACCEPT_ENCODING]: (conf, t) => [
    {
      name: "encodings",
      label: t("acceptEncodingList"),
      placeholder: t("acceptEncodingListPlaceholder"),
      defaultValue: conf.encodings as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "only_one_encoding",
      label: t("acceptEncodingOnlyOne"),
      placeholder: "",
      defaultValue: conf.only_one_encoding as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.KEY_AUTH]: (conf, t) => [
    {
      name: "query",
      label: t("keyAuthQuery"),
      placeholder: t("keyAuthQueryPlaceholder"),
      defaultValue: conf.query as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "header",
      label: t("keyAuthHeader"),
      placeholder: t("keyAuthHeaderPlaceholder"),
      defaultValue: conf.header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "delay",
      label: t("keyAuthFailDelay"),
      placeholder: t("keyAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "hide_credentials",
      label: t("keyAuthHideCredentials"),
      placeholder: t("keyAuthHideCredentialsPlaceholder"),
      defaultValue: conf.hide_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "keys",
      label: t("keyAuthValues"),
      placeholder: t("keyAuthValuesPlaceholder"),
      defaultValue: conf.keys as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.BASIC_AUTH]: (conf, t) => [
    {
      name: "authorizations",
      label: t("basicAuthList"),
      placeholder: t("basicAuthListPlaceholder"),
      defaultValue: conf.authorizations as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "delay",
      label: t("basicAuthFailDelay"),
      placeholder: t("basicAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "hide_credentials",
      label: t("basicAuthHideCredentials"),
      placeholder: t("basicAuthHideCredentialsPlaceholder"),
      defaultValue: conf.hide_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
  ],
  [PluginCategory.JWT]: (conf, t) => [
    {
      name: "header",
      label: t("jwtAuthHeader"),
      placeholder: t("jwtAuthHeaderPlaceholder"),
      defaultValue: conf.header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "query",
      label: t("jwtAuthQuery"),
      placeholder: t("jwtAuthQueryPlaceholder"),
      defaultValue: conf.query as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "cookie",
      label: t("jwtAuthCookie"),
      placeholder: t("jwtAuthCookiePlaceholder"),
      defaultValue: conf.cookie as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "auth_path",
      label: t("jwtSignPath"),
      placeholder: t("jwtSignPathPlaceholder"),
      defaultValue: conf.auth_path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "delay",
      label: t("jwtAuthFailDelay"),
      placeholder: t("jwtAuthFailDelayPlaceholder"),
      defaultValue: conf.delay as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "algorithm",
      label: t("jwtSignAlgorithm"),
      placeholder: "",
      defaultValue: conf.algorithm as string,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["HS256", "HS512"], false),
    },
    {
      name: "secret",
      label: t("jwtAuthSecret"),
      placeholder: t("jwtAuthSecretPlaceholder"),
      defaultValue: conf.secret as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.COMBINED_AUTH]: (conf, t) => [
    {
      name: "authorizations",
      label: t("combinedAuthAuthorizations"),
      placeholder: "",
      defaultValue: conf.authorizations as [],
      span: 6,
      category: ExFormItemCategory.COMBINED_AUTHS,
    },
  ],
  [PluginCategory.LIMIT]: (conf, t) => [
    {
      name: "type",
      label: t("limitCategory"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["rate", "inflight"], true),
    },
    {
      name: "tag",
      label: t("limitTag"),
      placeholder: "",
      defaultValue: conf.tag as string,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["cookie", "header", "query", "ip"], true),
    },
    {
      name: "key",
      label: t("limitKey"),
      placeholder: t("limitKeyPlaceholder"),
      defaultValue: conf.key as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "max",
      label: t("limitMax"),
      placeholder: t("limitMaxPlaceholder"),
      defaultValue: conf.max as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "interval",
      label: t("limitInterval"),
      placeholder: t("limitIntervalPlaceholder"),
      defaultValue: conf.interval as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "weight",
      label: t("limitWeight"),
      placeholder: t("limitWeightPlaceholder"),
      defaultValue: conf.weight as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
  ],
  [PluginCategory.IP_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("ipRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "ip_list",
      label: t("ipList"),
      placeholder: t("ipListPlaceholder"),
      defaultValue: conf.ip_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("ipRestrictionMessage"),
      placeholder: t("ipRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.GEO_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("geoRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny", "reporting"], true),
    },
    {
      name: "country_codes",
      label: t("geoRestrictionCountryCodes"),
      placeholder: t("geoRestrictionCountryCodesPlaceholder"),
      defaultValue: conf.country_codes as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("geoRestrictionMessage"),
      placeholder: t("geoRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.REFERER_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("refererRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "referer_list",
      label: t("refererList"),
      placeholder: t("refererListPlaceholder"),
      defaultValue: conf.referer_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("refererRestrictionMessage"),
      placeholder: t("refererRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.UA_RESTRICTION]: (conf, t) => [
    {
      name: "type",
      label: t("uaRestrictionMode"),
      placeholder: "",
      defaultValue: conf.type as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["allow", "deny"], true),
    },
    {
      name: "ua_list",
      label: t("uaList"),
      placeholder: t("uaListPlaceholder"),
      defaultValue: conf.ua_list as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "message",
      label: t("uaRestrictionMessage"),
      placeholder: t("uaRestrictionMessagePlaceholder"),
      defaultValue: conf.message as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.CSRF]: (conf, t) => [
    {
      name: "token_path",
      label: t("csrfTokenPath"),
      placeholder: t("csrfTokenPathPlaceholder"),
      defaultValue: conf.token_path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "name",
      label: t("csrfName"),
      placeholder: t("csrfNamePlaceholder"),
      defaultValue: conf.name as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "key",
      label: t("csrfKey"),
      placeholder: t("csrfKeyPlaceholder"),
      defaultValue: conf.key as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "ttl",
      label: t("csrfTtl"),
      placeholder: t("csrfTtlPlaceholder"),
      defaultValue: conf.ttl as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.CORS]: (conf, t) => [
    {
      name: "path",
      label: t("corsPath"),
      placeholder: t("corsPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_origin",
      label: t("corsAllowOrigin"),
      placeholder: t("corsAllowOriginPlaceholder"),
      defaultValue: conf.allow_origin as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_methods",
      label: t("corsAllowMethods"),
      placeholder: t("corsAllowMethodsPlaceholder"),
      defaultValue: conf.allow_methods as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_headers",
      label: t("corsAllowHeaders"),
      placeholder: t("corsAllowHeadersPlaceholder"),
      defaultValue: conf.allow_headers as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "allow_credentials",
      label: t("corsAllowCredentials"),
      placeholder: "",
      defaultValue: conf.allow_credentials as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "max_age",
      label: t("corsMaxAge"),
      placeholder: t("corsMaxAgePlaceholder"),
      defaultValue: conf.max_age as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "expose_headers",
      label: t("corsExposeHeaders"),
      placeholder: t("corsExposeHeadersPlaceholder"),
      defaultValue: conf.expose_headers as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
  ],
  [PluginCategory.RESPONSE_HEADERS]: (conf, t) => [
    {
      name: "add_headers",
      label: t("responseHeadersAddHeader"),
      placeholder: t("responseHeadersAddHeaderPlaceholder"),
      defaultValue: conf.add_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers",
      label: t("responseHeadersSetHeader"),
      placeholder: t("responseHeadersSetHeaderPlaceholder"),
      defaultValue: conf.set_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "remove_headers",
      label: t("responseHeadersRemoveHeader"),
      placeholder: t("responseHeadersRemoveHeaderPlaceholder"),
      defaultValue: conf.remove_headers as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
    {
      name: "rename_headers",
      label: t("responseHeadersRenameHeader"),
      placeholder: t("responseHeadersRenamePlaceholder"),
      defaultValue: conf.rename_headers as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "set_headers_not_exists",
      label: t("responseHeadersSetHeaderNotExists"),
      placeholder: t("responseHeadersSetHeaderNotExistsPlaceholder"),
      defaultValue: conf.set_headers_not_exists as string[],
      span: 6,
      category: ExFormItemCategory.KV_LIST,
    },
    {
      name: "mode",
      label: t("responseHeadersMode"),
      placeholder: t("responseHeadersModePlaceholder"),
      defaultValue: conf.mode as string,
      span: 6,
      category: ExFormItemCategory.RADIOS,
      options: newStringOptions(["upstream", "response"], true),
    },
  ],
  [PluginCategory.SUB_FILTER]: (conf, t) => [
    {
      name: "path",
      label: t("subFilterPath"),
      placeholder: t("subFilterPathPlaceholder"),
      defaultValue: conf.path as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "status_codes",
      label: t("subFilterStatusCodes"),
      placeholder: t("subFilterStatusCodesPlaceholder"),
      defaultValue: conf.status_codes as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "filters",
      label: t("subFilterFilters"),
      placeholder: t("subFilterFiltersPlaceholder"),
      defaultValue: conf.filters as string[],
      span: 6,
      category: ExFormItemCategory.TEXTS,
    },
  ],
  [PluginCategory.IMAGE_OPTIM]: (conf, t) => [
    {
      name: "output_types",
      label: t("imageOptimOutputTypes"),
      placeholder: t("imageOptimOutputTypesPlaceholder"),
      defaultValue: conf.output_types as string,
      span: 6,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "png_quality",
      label: t("imageOptimPngQuality"),
      placeholder: t("imageOptimPngQualityPlaceholder"),
      defaultValue: conf.png_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "jpeg_quality",
      label: t("imageOptimJpegQuality"),
      placeholder: t("imageOptimJpegQualityPlaceholder"),
      defaultValue: conf.jpeg_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "avif_quality",
      label: t("imageOptimAvifQuality"),
      placeholder: t("imageOptimAvifQualityPlaceholder"),
      defaultValue: conf.avif_quality as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "avif_speed",
      label: t("imageOptimAvifSpeed"),
      placeholder: t("imageOptimAvifSpeedPlaceholder"),
      defaultValue: conf.avif_speed as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
  ],
  [PluginCategory.TRAFFIC_SPLITTING]: (conf, t) => [
    {
      name: "upstream",
      label: t("trafficSplittingUpstream"),
      placeholder: t("trafficSplittingUpstreamPlaceholder"),
      defaultValue: conf.upstream as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "weight",
      label: t("trafficSplittingWeight"),
      placeholder: t("trafficSplittingWeightPlaceholder"),
      defaultValue: conf.weight as number,
      span: 3,
      category: ExFormItemCategory.NUMBER,
    },
    {
      name: "stickiness",
      label: t("trafficSplittingStickiness"),
      placeholder: t("trafficSplittingStickinessPlaceholder"),
      defaultValue: conf.stickiness as boolean,
      span: 3,
      category: ExFormItemCategory.RADIOS,
      options: newBooleanOptions(),
    },
    {
      name: "sticky_cookie",
      label: t("trafficSplittingStickyCookie"),
      placeholder: t("trafficSplittingStickyCookiePlaceholder"),
      defaultValue: conf.sticky_cookie as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "sticky_header",
      label: t("trafficSplittingStickyHeader"),
      placeholder: t("trafficSplittingStickyHeaderPlaceholder"),
      defaultValue: conf.sticky_header as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
    {
      name: "matcher",
      label: t("trafficSplittingMatcher"),
      placeholder: t("trafficSplittingMatcherPlaceholder"),
      defaultValue: conf.matcher as string,
      span: 3,
      category: ExFormItemCategory.TEXT,
    },
  ],
};
